// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pokébase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-purple-50 via-purple-50 to-purple-100 dark:from-purple-950 dark:via-purple-900 dark:to-purple-800`}
      >
        <header className="sticky top-0 z-50 bg-white/80 dark:bg-purple-950/80 backdrop-blur border-b border-purple-200 dark:border-purple-800">
          <div className="max-w-6xl mx-auto px-6 py-4 flex flex-col sm:flex-row items-center justify-between gap-4">
            <h1 className="text-4xl font-bold text-purple-900 dark:text-purple-100">
              PokéBase
            </h1>

            <nav className="flex gap-6 text-lg font-medium">
              <Link className="hover:text-purple-600" href="/pokemon">Pokémon</Link>
              <Link className="hover:text-purple-600" href="/locations">Locations</Link>
              <Link className="hover:text-purple-600" href="/moves">Moves</Link>
              <Link className="hover:text-purple-600" href="/generations">Generations</Link>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
